### ISSUE TITLE
cannot drag & drop stack parameters

### ISSUE THREAD

**Issue by hiroEsaki** [AlphaMoonbaseBerlin/TD_TauCeti_Presetsystem#22]
I use TD 2022.28040
and Preset Manager ver 4.34
I cannot d&d to record stack parameters.

I can record on PM ver 4.23

**Comment by AlphaMoonbaseBerlin** [comment]
I updated the way drag and drop works by implementing the new Drag and Drop callbacks.
It seems like that in 28040 this does not work yet.
28040 is quite an old version so I recommend updating.
I will see if I can make a quick hotfix, otherwise please update to at least 2022.32660 which is the current development-enviropnment for TauCeti.

**Comment by hiroEsaki** [comment]
Thank you for your reply.

I am sorry for using your time because I have been using an older version.
