### ISSUE TITLE
Override preset from parameters in Interact tab

### ISSUE THREAD

**Issue by function-store** [AlphaMoonbaseBerlin/TD_TauCeti_Presetsystem#24]
Currently you can add and remove presets from the Interact parameter tab which is cool.
To override the currently selected preset you need to type in the same name (or use the UI of course).

My proposal would be, if there is an empty field for Presetname, take the current Preset name.

In the parexec this modification does the trick:
```python
...
	elif par.name == "Interactrecord":
		name = parent().par.Interactrecordpresetname.eval()
		if name == '':
			name = parent().par.Interactrecordpresetname.eval()
		parent().Record_Preset(
			name
		)
...
```

Alternatively an additional Pulse would do the trick too.

**Comment by AlphaMoonbaseBerlin** [comment]
Good catch @function-store 
I instead opted with adding an additional Update-Parameter as I feel like it might not be super intuitive that this would work.
I first though about using a strMenu, but this also would be confusing as name and id do not have to be the same, and the stringMenu showing the ID instead of the name.
![grafik](https://github.com/user-attachments/assets/b720db7f-b95d-4d6e-92ff-5ee646abce63)
